# -*- coding: utf-8 -*-
"""Exposys_Data_Lab_cybersecurity_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QtI4rtEv5Ixz8QhtY7QncszOUzU-E5Xl
"""

pip install pycryptodome

from Crypto.Cipher import DES3
from Crypto.Random import get_random_bytes
from hashlib import md5

def encrypt_image(original_file_path, encrypted_file_path, key):
    # Generate a random IV (Initialization Vector)
    iv = get_random_bytes(8)

    # Key for performing Triple DES algorithm
    key_hash = md5(key.encode('ascii')).digest()

    # Adjust key parity of generated Hash Key for Final Triple DES Key
    tdes_key = DES3.adjust_key_parity(key_hash)

    # Cipher with integration of Triple DES key
    cipher = DES3.new(tdes_key, DES3.MODE_CBC, iv)

    # Open & read original image file
    with open(original_file_path, 'rb') as input_file:
        file_bytes = input_file.read()

        # Calculate the padding needed
        padding_length = 8 - (len(file_bytes) % 8)
        padded_bytes = file_bytes + bytes([padding_length] * padding_length)

        # Perform Encryption operation
        encrypted_bytes = cipher.encrypt(padded_bytes)

    # Write IV and encrypted image to specified path
    with open(encrypted_file_path, 'wb') as output_file:
        output_file.write(iv)
        output_file.write(encrypted_bytes)

    print('Image encrypted and saved to:', encrypted_file_path)

def decrypt_image(encrypted_file_path, decrypted_file_path, key):
    # Open & read encrypted image file
    with open(encrypted_file_path, 'rb') as input_file:
        # Read the IV from the first 8 bytes of the file
        iv = input_file.read(8)

        # Key for performing Triple DES algorithm
        key_hash = md5(key.encode('ascii')).digest()

        # Adjust key parity of generated Hash Key for Final Triple DES Key
        tdes_key = DES3.adjust_key_parity(key_hash)

        # Cipher with integration of Triple DES key
        cipher = DES3.new(tdes_key, DES3.MODE_CBC, iv)

        # Read the rest of the file for decryption
        encrypted_bytes = input_file.read()

        # Perform Decryption operation
        decrypted_bytes = cipher.decrypt(encrypted_bytes)

        # Remove padding
        padding_length = decrypted_bytes[-1]
        decrypted_bytes = decrypted_bytes[:-padding_length]

    # Write decrypted image to specified path
    with open(decrypted_file_path, 'wb') as output_file:
        output_file.write(decrypted_bytes)

    print('Image decrypted and saved to:', decrypted_file_path)

# Prompt user for file paths and encryption/decryption key
operation = input('Choose operation to be done:\n\t1- Encryption\n\t2- Decryption\nYour Choice: ')

if operation == '1':  # Encryption
    original_file_path = input('Enter the path of the original image file: ')
    encrypted_file_path = input('Enter the path where you want to save the encrypted image file: ')
    key = input('Enter your secret key for encryption: ')

    encrypt_image(original_file_path, encrypted_file_path, key)

elif operation == '2':  # Decryption
    encrypted_file_path = input('Enter the path of the encrypted image file: ')
    decrypted_file_path = input('Enter the path where you want to save the decrypted image file: ')
    key = input('Enter your secret key for decryption: ')

    decrypt_image(encrypted_file_path, decrypted_file_path, key)